Develop tristan
TristanBrattinga/anno-amsterdam pull request #19
Opened 2024-06-02 07:56 UTC by TristanBrattinga

Added navbar and sidebar to layout
Added buildingcard popup

2024-06-02 13:07 UTC, mtdvlpr requested changes

2024-06-02 13:07 UTC, mtdvlpr commented on apps/web/src/lib/components/CardPopup.svelte
> +							   xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAADsQAAA7EB9YPtSQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAoVSURBVHi
Maybe extract these image data strings to constants to clearify the code?

2024-06-02 13:07 UTC, mtdvlpr commented on apps/web/src/lib/components/Map.svelte
> +				d="M29 15H27.9575C27.7175 12.1743 26.486 9.5245 24.4808 7.51924C22.4755 5.51398 19.8257 4.28247 17 4.0425V3C17 2.73478 16.8946 2.48043 16.7071 2.29289C16.5196 2.10536 16.2652 2 16 2C15.7348 2 15.
Maybe make this SVG a component to improve readability?

2024-06-02 13:07 UTC, mtdvlpr commented on apps/web/src/lib/components/Sidebar.svelte
> +	<p>Filters</p>
Add these strings to the i18n config with English translations

2024-06-02 13:07 UTC, mtdvlpr commented on apps/web/src/lib/styles/main.scss
> +}
Is already present in the reset.scss

2024-06-02 13:32 UTC, TristanBrattinga commented on apps/web/src/lib/components/Map.svelte
> +				d="M29 15H27.9575C27.7175 12.1743 26.486 9.5245 24.4808 7.51924C22.4755 5.51398 19.8257 4.28247 17 4.0425V3C17 2.73478 16.8946 2.48043 16.7071 2.29289C16.5196 2.10536 16.2652 2 16 2C15.7348 2 15.
Done! Heb een icons dir gemaakt waar de icons vandaan kunnen komen

2024-06-02 13:55 UTC, TristanBrattinga commented on apps/web/src/lib/components/Sidebar.svelte
> +	<p>Filters</p>
Ik heb nu alleen ff het woord filters erin verwerkt. Laten we morgen samen ff de echte filters erin stoppen

2024-06-03 07:23 UTC, mtdvlpr approved these changes
Nice work! One small thing and then it's good to go :)

2024-06-03 07:23 UTC, mtdvlpr commented on apps/web/src/routes/[lang=lang]/(app)/map/+page.ts
> +	const title = LL.filters();
This is the page title, so should be "map view" or something similar.

2024-06-03 10:07 UTC, merged